### ISSUE TITLE
Allow users and those in their trusted circles to identify and log objects/buildings/etc with a geophysical location on the shared map

### ISSUE THREAD

**Issue by hannahhubbard** [meitar/better-angels#101]
Add a function so users of Buoy can work together to record the location of physical items and structures that may be important to their safety on a saved GPS map. For example, a user's trusted circle of responders may to work together to identify ATMs, grocery stores, police stations, shelters, surveillance cameras, homes, and more, and mark them on the shared map, so in the event of a crisis, the alerter will have immediate access to this information. Almost like an escape pathway, in some cases. Make it so the users can do this in real time during a crisis community response or before hand on a shared map.

**Comment by meitar** [comment]
Can you elaborate on how this differs from #18?

**Comment by hannahhubbard** [comment]
Ah. No difference. I will look at #18 and add anything that may apply to this there. Should I close?
