### ISSUE TITLE
Audio Recording issue

### ISSUE THREAD

**Issue by mata2991** [meitar/better-angels#102]
Noverse Bug Reporting Template
==============================

Title: Audio Recording Issue

Class:
e.g. "Feature Request", "System Error", "Serious Bug"

Date:   12/30/15        
Reported By:   Daniel Mata
Email:      matadaniel.92@gmail.com

Product A: Samsung laptop                        Version: Windows 10
Product B:   Lenovo thinkpad                      Version: Windows 7
Product C:  Samsung Tablet                       Version:  
Product D:  Sony Xperia phone                    Version
Platform:                                                       Version:
Browser:     Google Chrome for all of them    Version:
URL:        

Is it reproducible: Yes / Occasionally / One Time / No

Description
===========
Uploaded a audio recording and it was labeled under video recordings. Also, I wasn't able to open it on my phone(Sony Xperia) and on another laptop (Lenovo Thinkpad). The laptop is running on windows 7, I'm not sure what my phone is running on.

Steps to Produce/Reproduce
--------------------------
Step 1: Record Audio
Step 2: Open file

Expected Results
----------------
Opening the file and hearing audio

Actual Results
--------------
Under product A and C I was able to access the file and hear the audio. 

Under Product B I received an error from Windows Media Player "Windows Media Player cannot play the file. The Player might not support the file or might not support the codec that was used to compress the file" <a href="http://imgur.com/Wb34hbi">This is the error I received</a>

Under product D I received "Can't open file" error. This is the error -> <iframe src="//giphy.com/embed/H7jPCB0w2ms2A" width="480" height="270" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/H7jPCB0w2ms2A">via GIPHY</a></p>

  
Workarounds
-----------

Attachments
-----------

Other Information
-----------------

**Comment by meitar** [comment]
> Step 1: Record Audio
> Step 2: Open file

I don't think you understand the point of a "steps to reproduce" section of a bug reporting template.
