### ISSUE TITLE
not able to type in a scheduled time

### ISSUE THREAD

**Issue by mata2991** [meitar/better-angels#112]
when you go to schedule a alert time, the directions gives the user an option to "type a specific date and time in the "YYYY/MM/DD HH:mm format." 

I expect to be able to time in that format, instead I'm not able to type at all.

**Comment by meitar** [comment]
I had no problem doing so.

![tmp_6268-screenshot_2016-01-18-13-35-43975183907](https://cloud.githubusercontent.com/assets/18677/12402196/85a82664-bde8-11e5-8142-6be02c4f0491.png)
