### ISSUE TITLE
Add a function to push out for instant crowdsourced funding for individuals in crisis situations.

### ISSUE THREAD

**Issue by hannahhubbard** [meitar/better-angels#114]
This has some serious security and identity considerations, but could admins opt to push notifications of crisis alerts out to a crowdsourcing platform that could then be pushed out via social media. This could demonstrate real needs in real time and opportunities to help individuals in crisis. Admins could define for themselves how this might work, and Buoy users could opt in or out of this option. Admins may need to oversee this with a confirmation model to make sure that users are not pretending to be in crisis just to receive funding. This may need to be a separate piece of software (and we need to check to see if this is already available) that Buoy can connect to. A thought with consideration needed as to whether this would even work and whether it might compromise the foundational identity component of Buoy.

**Comment by meitar** [comment]
This [feels way out of scope](https://en.wikipedia.org/wiki/Scope_creep) to me.
