### ISSUE TITLE
"Fatal error: Cannot access private property WP_Buoy_Settings::$meta_key in /home/tech4j/public_html/wp-content/plugins/buoy/uninstall.php on line 30" when attempting to uninstall Buoy

### ISSUE THREAD

**Issue by scottburck** [meitar/better-angels#120]
When trying to uninstall the Buoy plugin from the Tech for Justice WordPress (for testing purposes), the above error results. The issue is consistent across different computers and browsers. Please see the attached video screen capture illustrating the steps to reproduce this problem. 

[Buoy Uninstall Bug.zip](https://github.com/meitar/better-angels/files/105813/Buoy.Uninstall.Bug.zip)

**Comment by meitar** [comment]
Good catch, thanks @scottburck. Should be fixed in bde95f4701e5651ad8faf78d19c8191d03504a5a and bundled with the next release.
