### ISSUE TITLE
When adding a new user to a Buoy team whose username contains a space, the username must be typed manually rather than selected through the drop-down box of available users

### ISSUE THREAD

**Issue by scottburck** [meitar/better-angels#121]
While testing Buoy on the Tech for Justice WordPress and attempting to add users to a team whose username contains a space (i.e. "First Last"), the "Add a team member" drop-down box displays the username as "first-last" rather than "First Last". 

Buoy will not allow the user to be added to the team unless this field is manually changed to the correct username, i.e. "First Last". As I am new to writing bug reports, please let me know if this is not sufficiently descriptive of the problem and I would be happy to include a screen capture documenting the issue.

**Comment by meitar** [comment]
Another good catch, thank you again @scottburck. This was easily reproducible and is patched in 83a2e5bd9af64495bf78bb2a31376aab74c6332b, which includes unit tests to ensure it any regression is caught in the future. This is ready for bundling into the next release.
