### ISSUE TITLE
Sending a Buoy Chat message results in an error on all devices

### ISSUE THREAD

**Issue by TechForJustice** [meitar/better-angels#125]
Devices tested and reproduced on: 
(Android version: 5.1.1, Google Chrome 47.0.2526.83)
(android version: 5.1.1, Samsung Galaxy 6 edge +, chrome 47.0.2526.83)
(Android version 6.0.1, Google Nexus 6P, Chrome 47.0.2526.83)
(Android 5.1.1, Chrome 47.0.2526.83)
(Samsung Galaxy Note 3, Android 4.4.2, Internet 1.5.28)
(including Android 5.1.1 using Google Chrome 47.0.2526.83)

Sending a Buoy Chat message results in the following error on all devices. 
User Steps: Received alert email, clicked link, tapped respond, chat room opened up. Typed in message and then received error : 

Warning: array_filter() expects parameter 1 to be array, boolean given in /home/tech4j/public_html/wp-includes/pluggable.php on line 1409

Warning: Cannot modify header information - headers already sent by (output started at /home/tech4j/public_html/wp-includes/pluggable.php:1409) in /home/tech4j/public_html/wp-includes/pluggable.php on line 1228

**Comment by meitar** [comment]
Note that this probably occurs only when using the "Built-in (WordPress Commenting System)" chat provider.

**Comment by TechForJustice** [comment]
As an admin, I used Tlk.io as the chat system instead of wordpress comments, and did not receive the error above.

**Comment by unquietpirate** [comment]
I tested Buoy today on three mobile devices, two laptops, and a desktop (sorry, I didn't get the specs on any of them, but I can if necessary), using the buoyde.vps server, and Tlk.io as the chat system. 

My testers and I did not run into this error on any devices. However, we did not test the WordPress Commenting System, only Tlk.io.

**Comment by meitar** [comment]
Is this still a problem? There have been a lot of updates to the built-in chat system. I can not reproduce this error, so I'm closing this issue. If someone can confirm that this is still a problem, they can reopen it.
