### ISSUE TITLE
No results are shown on the “Active Alert” page.

### ISSUE THREAD

**Issue by TechForJustice** [meitar/better-angels#130]

**Comment by meitar** [comment]
???

What is a "result" here?

**Comment by TechForJustice** [comment]
Sorry for not describing this issue better... Based on our chat history while testing the app, it seems that the problem was that users who do not confirm their email address before an alert is sent will not receive the alert, and have no way of viewing it.

**Comment by meitar** [comment]
Oh I see, so if an alerter invites someone by email to join their team, then if that email account is not associated with a user ID of an existing account, then if the alterer sends an alert to the team that they just added the invited person to *before* that person registers for their account, the alert sent to that team does not get sent to the invited user.

Are those the exact conditions you intended to describe?

**Comment by TechForJustice** [comment]
Almost exactly, except the email address is already associated with a WordPress user ID but has not yet been added to Buoy.

When a new user is added to a Buoy team, they get an email with the subject line "[User] wants you to join [Buoy Team Name]." If the link contained in this email is not clicked, the alert does not get sent to that invited user.

**Comment by meitar** [comment]
That's not a bug. Alerts are not sent to users who have been *invited* to join a team, only to users who have *confirmed* that they want to accept a given invitation.
