### ISSUE TITLE
Chat window visibility issues when using Tlk.io as chat provider

### ISSUE THREAD

**Issue by TechForJustice** [meitar/better-angels#131]
When using Tik.io for chat, there are some visibility issues that impact usability, especially on smartphones:

- Half of the chat screen appears cut off by white space on both Android and OS X versions of Chrome.

- Tik.io's floating indicator of how many members are in the chat seems to cover part of the chat window.

- Tik.io's chatroom name (for example, buoy_8718b1cde746b755ec23) is displayed on the chat screen in large type and makes viewing the chat history difficult on smartphone screens.

**Comment by meitar** [comment]
Screenshots might make your communication more communicative: http://lifehacker.com/5994516/how-to-take-a-screenshot-on-android

**Comment by TechForJustice** [comment]
For some users, he bottom half of the screen is cut off by white space, as seen below:

![picture1](https://cloud.githubusercontent.com/assets/11147797/12969461/67e58e76-d046-11e5-9264-e6bf73210de3.png)
