### ISSUE TITLE
As a responder, “Go to my location” pans map to the alert issuer’s location, not the responder's location.

### ISSUE THREAD

**Issue by meitar** [meitar/better-angels#135]
Originally reported by @TechForJustice in #129 with no description titled:

> When accessing the map to respond to an active alert (with the map hidden) by pressing “go to my location”, nothing happens. When pressed with the map open, “Go to my location” directs to the alert issuer’s location, not the user’s location.

**Comment by meitar** [comment]
@TechForJustice, please clarify "user" in this issue report.

**Comment by TechForJustice** [comment]
"User" was referring to a team member who is receiving an alert, not the alert's sender. 

As an alert recipient, tapping "go to my location" does not pan the map to one's own current location (as would normally happen if they were using Google Maps); instead, it pans the map to the location of the person who issued the alert.

**Comment by meitar** [comment]
Okay, I updated the title of this issue so someone reading it need not be a telepath to understand it. ;)
