### ISSUE TITLE
Uploaded media is stored in WordPress Media library and viewable by WordPress users

### ISSUE THREAD

**Issue by TechForJustice** [meitar/better-angels#144]
It seems as if all media uploaded by Buoy users is now visible to the organization’s admins and is stored in their WordPress Media Library. This could pose a privacy risk. There should also be a section in the menu for all the media that the Alerter saves so it will be easy to find.  

![picture1](https://cloud.githubusercontent.com/assets/11147797/12969521/545429b6-d047-11e5-8bae-de3eb9dacc3f.png)

**Comment by meitar** [comment]
Admins are supposed to have access to all items in the site. Thatt's why they're admins. If you have multiple users on your site who don't need to be admins, you should change their role to something more appropriate. See also [WordPress Codex page on Roles](https://codex.wordpress.org/Roles_and_Capabilities).

**Comment by meitar** [comment]
> There should also be a section in the menu for all the media that the Alerter saves so it will be easy to find.

Please separate suggestions into their own issue tickets.
