### ISSUE TITLE
Unable to reply to chat messages (using tik.io as chat provider)

### ISSUE THREAD

**Issue by TechForJustice** [meitar/better-angels#147]
Unable to post anything on the chat. When attempting to reply to chat messages, the send button does not appear.

![picture1](https://cloud.githubusercontent.com/assets/11147797/12969659/3c098a52-d049-11e5-8979-290d2bc17069.png)

**Comment by meitar** [comment]
What were the differences between your device and the devices of whoever it was that was clearly able to send messages, since your screenshot shows their chat?

**Comment by meitar** [comment]
Also, how did you get to https://tlk.io? You're npt even at a Buoy in that screenshot….

**Comment by meitar** [comment]
With no response for over three weeks, I'm closing this issue since I can not reproduce it.
