### ISSUE TITLE
Unable to delete teams as Admin

### ISSUE THREAD

**Issue by christyleos** [meitar/better-angels#148]
I attempted to delete teams as an admin and was unable to do so. 

Steps: Updated the Buoy plugin > clicked on my teams > selected all then selected move to trash > press apply> then received a error screen

Software version: 5.1.1
Browser: Google chrome 48.0.2564.95

![screenshot 57](https://cloud.githubusercontent.com/assets/15221858/12982808/1476dcd4-d0ac-11e5-886c-6431d9c86a5e.png)
![screenshot 58](https://cloud.githubusercontent.com/assets/15221858/12982809/1478c01c-d0ac-11e5-9244-ee2c30129ccf.png)

**Comment by meitar** [comment]
I just tried doing this on the staging server without issue. Try it there (or any other WordPress install) and see if it works. If it does, the issue has something to do with your own site's setup.

**Comment by christyleos** [comment]
I was able to delete all the teams except for one: 
![screenshot 63](https://cloud.githubusercontent.com/assets/15221858/13153057/b264c18c-d637-11e5-9fd8-52c1ef2b3e29.png)

Then I tried it on the staging server like you said, and it would not let me delete the team (I select move to trash and it doesn't). 
![screenshot 64](https://cloud.githubusercontent.com/assets/15221858/13153278/d6bfb55e-d638-11e5-9eb8-536eb88af09a.png)

Am I not allowed to delete the default team?

**Comment by meitar** [comment]
> Am I not allowed to delete the default team?

I wrote code that prevents a user from leaving themselves with no teams. You can delete this team if you first make another.

This issue does not reflect a bug, despite conflicting reports. You first reported 403 Forbidden errors but then report something else, so I'm ignoring this unless the report becomes sane.

**Comment by christyleos** [comment]
It was giving me 403 Forbidden errors initially but it seems that is no longer the case and I was able to delete the teams I wanted to. It may have been a wordpress issue. Thanks for the info.
