### ISSUE TITLE
No send button and unable to see chat when responding to alert

### ISSUE THREAD

**Issue by Sasykora** [meitar/better-angels#153]
![screenshot_2016-02-11-14-45-56](https://cloud.githubusercontent.com/assets/17184327/13087622/7ed353cc-d4ae-11e5-8711-10b7522d63bf.png)
![screenshot_2016-02-11-14-37-43](https://cloud.githubusercontent.com/assets/17184327/13087662/ab3e2626-d4ae-11e5-9002-5e8053c5de20.png)

I received the alert but was given what is in the screenshot when opened.
I was on a Galaxy s5 running android 5.0 with the android internet browser.

**Comment by meitar** [comment]
Tlk.io doesn't show a send button. To send a message, you just type it and press the return key.
