### ISSUE TITLE
Error upon installation: "Parse error: syntax error, unexpected T_STATIC, expecting ')' in …buoy.php on line 330"

### ISSUE THREAD

**Issue by webpdq** [meitar/better-angels#160]
Parse error: syntax error, unexpected T_STATIC, expecting ')' in …/wp-content/plugins/buoy/buoy.php on line 330

Tried to install on my site, all up to date.. plugins, wp core etc. 

http://webpdq.com/belles/

**Comment by meitar** [comment]
What version of PHP is your site running? Buoy requires PHP 5.3 or later as per [its Installation notes](https://wordpress.org/plugins/buoy/installation/).

**Comment by webpdq** [comment]
I updated it. Thanks. Working now.

On 2/27/2016 3:03 PM, Meitar M. wrote:
>
> What version of PHP is your site running? Buoy requires PHP 5.3 or 
> later as per its Installation notes 
> <https://wordpress.org/plugins/buoy/installation/>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/meitar/better-angels/issues/160#issuecomment-189715197>.
>

-- 
"Never doubt that a small group of thoughtful, committed citizens can 
change the world; indeed, it's the only thing that ever has." - Margaret 
Mead
