### ISSUE TITLE
Feature request: Alert user when data entered in phone number field is not usable

### ISSUE THREAD

**Issue by unquietpirate** [meitar/better-angels#25]
I found that I was able to enter any data at all into the "Emergency SMS" field. For example, I typed "VERIZON 555.555.1234" and this was accepted. Although the field can accept any format of phone number, might be valuable to alert users when they've entered a string that will not result in them being able to receive SMS notifications.

**Comment by meitar** [comment]
Interestingly, that value actually ends up becoming `3038176530` because before we actually send an SMS, we strip everything except digits. :) So technically a value like `VERIZON 555.555.1234` *is* an usable value.

That said, I do think an input mask would be helpful. Can you help me find a list of all possible acceptable telephone number input masks?

**Comment by unquietpirate** [comment]
Sure! The formats that immediately come to mind are:
(999) 000-0000
999-000-0000
999 000 0000
999.000.0000
9990000000

But I'm sure there are others. I'll Google for something more comprehensive. (I don't know anything about input masks, so I'm currently skimming this article: https://support.office.com/en-us/article/Control-data-entry-formats-with-input-masks-e125997a-7791-49e5-8672-4a47832de8da to try and get a sense of what I'm looking for.)

(P.S. Thank you for editing that phone number for me. I wasn't even thinking. :P)

**Comment by unquietpirate** [comment]
I don't understand everything that's being said here, so not sure if it's what you're looking for, but here's a thread about making input masks for telephone numbers: http://www.webdeveloper.com/forum/showthread.php?36984-input-mask-for-phone-number

And Wikipedia seems to confirm my list of acceptable US phone number formats: https://en.wikipedia.org/wiki/National_conventions_for_writing_telephone_numbers#United_States.2C_Canada.2C_and_other_NANP_countries (formats for other countries on that page also)
