### ISSUE TITLE
Re-label "Emergency txt (SMS)" field

### ISSUE THREAD

**Issue by unquietpirate** [meitar/better-angels#26]
Consider changing this field labeled "Emergency txt (SMS)" to "Phone Number" with descriptive text explaining this allows you to receive emergency alerts via text message (SMS). 

The purpose of a field simply labeled "Emergency txt (SMS)" may be unclear to new users who are just setting up their profiles and unfamiliar with the workings of the tool. Whereas a field labeled "Phone number" makes it clear they are expected to enter their phone number.

If possible, I would also put the "Phone Company" dropdown directly underneath the "Phone Number" field rather than in the Account Management section.

**Comment by meitar** [comment]
> If possible, I would also put the "Phone Company" dropdown directly underneath the "Phone Number" field rather than in the Account Management section.

This is possible but an unfortunate hassle in WordPress. I'm going to not do that for now simply due to priorities.
