### ISSUE TITLE
BUG: Only one Team Member is described as "pending" when all should be

### ISSUE THREAD

**Issue by unquietpirate** [meitar/better-angels#28]
I ran into this bug using Safari v. 9.0, and was able to replicate it using Firefox v. 41.0.1.

I was logged into the account "rebecca". On the page titled "Choose your team members" I typed the name "fox" and hit enter. In the "Remove a team member" section, "fox (pending)" appeared. This was the behavior I expected.

When I added another team member ("frog") and hit enter, "frog (pending)" appeared in the 
"Remove a team member" section below "fox". I expected this, but I also expected all other pending team members to continue to be described as "pending." However, "fox (pending)" also changed to simply "fox". "Frog" was now the only invited team member designated as "pending." 

I tried this several more times and, in each case, only the most recently invited team member retained the "pending" description. None of the listed team members in the attached screenshot has accepted an invitation to join my team.

![screen shot 2015-10-13 at 11 25 32 pm](https://cloud.githubusercontent.com/assets/4370462/10475542/05350ba0-7202-11e5-8d70-091fd376292a.png)

**Comment by unquietpirate** [comment]
As I'm playing with the invitation system more, I'm noticing some other weird behavior that I'm not entirely sure yet how to classify. For example: 

If I change a pending invitation from "real" to "fake", that team member is labeled "fake" but loses the "pending" descriptor. 

If I add a team member as "fake", and then change their status to "real" while their invitation is still pending, some or all of my other pending invited team members disappear.

I'm not yet sure what the pattern is here, but will keep playing with it…

**Comment by meitar** [comment]
Yeah, this is why I was complaining to you the other night that the guardian thing needs to be re-architected. There are four lists right now, but there really should only be one. If this is just a UI bug then I'll consider postponing invitation system re-architecting work, otherwise I think that should get prioritized so we have as solid foundation about this moving forward. :\

**Comment by unquietpirate** [comment]
Yeah, that makes sense. I was running into a lot of weird little bugs while playing with the invitation system. I didn't report every single one of them, because I'm guessing they're all symptoms of the larger architectural issue -- so I thought I'd hold off until we'd tackled that, and then see what (if any) of those bugs remain.

Not sure if this thread is the right place to discuss re-architecting. But I'm in agreement that, rather than having multiple lists, it makes the most sense to have a single list of team members who have various attribute options. This also seems like it gives us more flexibility for the future, in case we want to add additional attributes to team members that we haven't thought of yet.
