### ISSUE TITLE
BUG: Safari does not display Available Team Member drop-down

### ISSUE THREAD

**Issue by unquietpirate** [meitar/better-angels#29]
Using Safari v. 9.0, on the Choose Your Team Members page, the only way I've been able to add/invite another user to join my team is by typing their full username into the "Add a team member" field. No drop-down appears when I click in the field, nor when I start typing in it.

**Comment by meitar** [comment]
The HTML5 `<datalist>` element, which provides the drop-down menu, is [not supported by Safari](http://caniuse.com/#feat=datalist).
