### ISSUE TITLE
Privacy concerns re: Add Team Members drop-down listing all users on the system?

### ISSUE THREAD

**Issue by unquietpirate** [meitar/better-angels#31]
Not MVP but something we might want to think about for the future: 

Is displaying a drop-down list of all users on the system an issue for user privacy and/or spam? Should we require a user to know something about the people they are inviting to join their Team e.g. require an e-mail address, a phone number, or at least know the full username of the person they are searching for? 

Not sure how to deal with this elegantly, but not sure that we should display a complete list of all users of (a given instance of) the app to anybody who installs it. Any thoughts?

**Comment by meitar** [comment]
The trade-off here is that if you're not a privileged user of the system (and most users are not), then you won't be able to know who else is on the system that you can add to your team. Theoretically this can be handled out-of-band, by pre-existing friendships (a user emails someone privately asking for their username), but this complicates the set-up process. On the other hand, letting everyone see who else has accounts on the system can be considered an information disclosure vulnerability.

I think we should err on the side of caution. I will change this to reflect WordPress's default settings: only users who have privileged access to the system should be able to see a drop-down list that includes all users, while unprivileged users will no longer get the autocomplete benefits of such a list.

More discussion definitely needed on this, so I'm leaving this open and pinging @letzgolilkittykat for input.

**Comment by unquietpirate** [comment]
Okay. Agreed, erring on the side of caution seems better for now. 

Re: Connections being handled out-of-band option. My sense is that it's standard practice among social apps that you have to know someone's username (or other identifying info) before you can add them, but people do seem to sort that out relatively easily. (In fact, "Hey, are you someone I can call on in case of an emergency? If so, are you on this app and can I add you?" seems like a conversation one might want to have before inviting a person to their team, anyway.) 

Another idea, although I have mixed feelings about this 'cause Facebook, is that this might be a place where integration with something like Facebook could be helpful. The app could then suggest (or, at least, allow you to view) people you already know who are also using the app. This provides a bit of a middle ground between seeing all users and seeing no users. (I think this is pretty standard practice among many social apps also. "Import your contacts to see which of your friends are on Instagram!" etc. )

**Comment by unquietpirate** [comment]
Hm. Actually, maybe this is something that could be controlled as a per-user profile setting? i.e. "List me publicly as a responder." "Only allow people who already have me in their contacts to find me." "Only allow people who know my username and/or e-mail to find me." etc? I dunno, just spitballing.

**Comment by meitar** [comment]
> Actually, maybe this is something that could be controlled as a per-user profile setting? i.e. "List me publicly as a responder." "Only allow people who already have me in their contacts to find me." "Only allow people who know my username and/or e-mail to find me." etc? I dunno, just spitballing.

Scope creep alert.

We are not a contact management application.

**Comment by meitar** [comment]
> "List me publicly as a responder."

This seems the most workable suggestion so far.

**Comment by unquietpirate** [comment]
Okay. Maybe that should just be another toggle. "List me publicly as a responder" vs. "Don't list me publicly" (which requires someone to enter their full username in order to send them a Join My Team invite.)
