### ISSUE TITLE
cannot enter text when sending a custom alert

### ISSUE THREAD

**Issue by unquietpirate** [meitar/better-angels#47]
Samsung Galaxy. Stock Android browser v. 4.4.2. When attempting to send a custom alert, clicking on "text bubble" button brings up a text box, but user cannot enter any text

**Comment by meitar** [comment]
This seems to be a bug with Bootstrap's modals.

**Comment by meitar** [comment]
An apparently similar (if not identical) issue seems to be affecting iOS's Mobile Safari. Worth trying this out on desktop Safari and seeing if there's a similar issue.

**Comment by meitar** [comment]
Confirmed on Opera for Android as well. This is almost certainly something to do with WebKit since the AOSP browser, Safari, and Opera all use WebKit.
