### ISSUE TITLE
Can we add an option for non-emergency prevention advice / connections?

### ISSUE THREAD

**Issue by hannahhubbard** [meitar/better-angels#61]
When someone creates an account on Bouy, can we offer a link to further advice "pathways" or connections to real advocates for secret chats? This would allow those who do believe they may experience a dangerous situation to also access general and specialized information about how to prevent emergency situations, how to leave or improve their current situation, and connections to humans who can help provide support.

Is this something that would be better created as a separate application / system and connected to Buoy if desired by the individual Admin organization?

**Comment by meitar** [comment]
Yes. This is what WordPress is for. ;) An admin can/should provide such useful information on their website. They can do this by publishing a page on their website containing these resources as they would normally do even independent from Buoy.
