### ISSUE TITLE
"Install Buoy" Pop-up fails to disappear on mobile device

### ISSUE THREAD

**Issue by roseline1** [meitar/better-angels#84]
The "Install Buoy" pop-up fails to disappear even after adding the app to a mobile phone's home screen as the pop-up suggests. The pop-up interferes with the "respond" section/button of a chat room making it quite impossible to make further actions unless the "Show map" button is selected. Also, it remains a distraction on the Active Alerts page and Dashboard.

**Comment by meitar** [comment]
@roseline1 Thanks for reporting this. Commits a84aae47f2f467da02766e4a137090e36ea281d6 and b1ab49015a7eefe5c4e1715091f49abde1b59953 should fix this. Can you please test again and ensure the new "Dismiss" button, once pressed, prevents the installation prompt from appearing for a given user in subsequent loads?

**Comment by roseline1** [comment]
I have tested again and the "Dismiss" button seems to be effective. The "Install Buoy" pop-up has not reappeared after dismissing it.
