### ISSUE TITLE
sent an alert and the wrong time was displayed

### ISSUE THREAD

**Issue by mata2991** [meitar/better-angels#95]
I sent an alert around 10:25 pm 12/20/2015. The wrong time was displayed under the active alerts tab.
<a href="http://imgur.com/steFNui"> It displayed that the alert was at 4:20 am</a>

**Comment by meitar** [comment]
The page displays time based on the WordPress timezone; the staging site is set to GMT time. 10pm is 6 hours before GMT time, which is 4am. I'm betting you're in <a href="http://www.worldtimezone.com/utc/utc-0600.html">Central America, which is -6GMT</a>, thus account for the difference. This isn't the wrong time, it's the right time. What you're seeing is a time zone difference.
