### ISSUE TITLE
Remove a team member doesn't Match current team

### ISSUE THREAD

**Issue by mata2991** [meitar/better-angels#96]
When I accidentally removed a team from the  <a href="http://imgur.com/d9QoBu6">current team page</a> it didn't reflect on the <a href="http://imgur.com/G49cKNZ">remove a member page</a>.

Tansy-responder is under current team but not remove a member.
Daniel-responder is under remove a member but not current team. (this is the one I also removed from my team by accident, therefore its still showing up) Also when I try adding Daniel-responder back to my team, I'm not receiving a email to join the team.

**Comment by meitar** [comment]
The sequence of events here is not clear:

* What state was the system in at the beginning of the sequence?
* In what sequence did you take what actions?

Please read http://noverse.com/blog/2012/06/how-to-write-a-good-bug-report/ for guidance on how to write clear bug reports.

**Comment by mata2991** [comment]
I removed a team member but it still shows up under current team.

**Comment by mata2991** [comment]
Also under remove a team member, it only shows one team member rather than the whole team

**Comment by meitar** [comment]
> I removed a team member but it still shows up under current team.

This doesn't address a single question asked of your report nor does it add new information to the original report and so is equally useful (and useless) as the original report.

To reiterate, [those questions were](https://github.com/meitar/better-angels/issues/96#issuecomment-166203577):

> * What state was the system in at the beginning of the sequence?
> * In what sequence did you take what actions?

Please read the advice for writing a good report in http://noverse.com/blog/2012/06/how-to-write-a-good-bug-report/ and then actually follow said advice before writing another report or comment. Inactionable bug reports wastes my team and tests my patience, of which I have very little to start with.

**Comment by meitar** [comment]
> Also under remove a team member, it only shows one team member rather than the whole team

I cannot reproduce this issue. For the third (and final) time, please provide a *useful* bug report, which in this instance specifically includes at least a step-by-step detailed description of what actions you took from what starting state for this issue to present itself.
