### ISSUE TITLE
uploading video to chat room

### ISSUE THREAD

**Issue by mata2991** [meitar/better-angels#97]
was not able to upload a in the chat room

User 1 is using a mobile device and sent a crisis alert to user 2 -> user 2 joins the chat -> user 1 goes to upload media and records a video -> user 1 expected to have a video uploaded instead nothing was uploaded

did this 4 times

**Comment by meitar** [comment]
Please use this template for your next bug report: http://www.noverse.com/images/noverse-bug-reporting-template.txt
